### ISSUE TITLE
Moving out of contrib

### ISSUE THREAD

**Issue by garyb** [ethul/purescript-angular#31]
Hey @ethul, would you mind moving this back to being under your personal account? With it being in an experimental state, and neither @paf31 or I being particularly familiar with Angular, it's not something we can maintain or offer support on.

We're going to try and tidy up `contrib` a bit to stick to "production ready" libraries, and maybe even do away with it entirely at some point in favour of just using the core `purescript` org, and by then Pursuit should help solve the discoverability problem that we originally had when introducing `purescript-contrib`.

**Comment by ethul** [comment]
Will do. No problem on the transfer.

**Comment by ethul** [comment]
Done

**Comment by garyb** [comment]
Thanks!

**Comment by ethul** [comment]
Very welcome
